feat: change error casting in go113
cyrilgdn/terraform-provider-rabbitmq pull request #3
Opened 2020-12-07 02:56 UTC by AlphaWong

# objective
seems go 1.13 introduce a better way for error casting should we change the statement like my commit ?

# reason
seems the minimum go version is already >= 1.13

https://github.com/cyrilgdn/terraform-provider-rabbitmq/blob/master/.travis.yml#L7 

# reference
https://github.com/golang/go/wiki/ErrorValueFAQ

2020-12-13 17:54 UTC, cyrilgdn requested changes
Hi @AlphaWong ,

Thanks for opening this PR. Could you push again, Travis was disabled and didn't run. I enabled it back.

Tests currently don't pass without the suggestion I made (rabbithole does not return a pointer).

We can use this new syntax but, as I'm not a Go expert, it's still quite blurry for me with this pointer to a type :thinking:

2020-12-13 17:54 UTC, cyrilgdn commented on rabbitmq/util.go
> +	var errorResponse *rabbithole.ErrorResponse
```suggestion
	var errorResponse rabbithole.ErrorResponse
```

2020-12-14 13:57 UTC, AlphaWong commented
> Hi @AlphaWong ,
> 
> Thanks for opening this PR. Could you push again, Travis was disabled and didn't run. I enabled it back.
> 
> Tests currently don't pass without the suggestion I made (rabbithole does not return a pointer).
> 
> We can use this new syntax but, as I'm not a Go expert, it's still quite blurry for me with this pointer to a type 🤔

thx a lot

2021-01-01 20:47 UTC, cyrilgdn approved these changes
Thanks :+1: 

I merged master into your branch to fix the other error in the tests (was still executing some Hashicorp tests for the previous repository)

2021-01-01 20:47 UTC, merged